import { Link } from "wouter";
import { motion } from "framer-motion";
import { ArrowRight, Check, ChevronRight, Clock3, MapPin, ShieldCheck, Stethoscope, UsersRound } from "lucide-react";
import { AssistantCard, AppLayout, DoctorCard, HospitalCard, SearchBar, SectionHeading, TrustPill, VoiceReminderCard } from "@/components/DocxShell";
import { doctors, hospitals, testimonials } from "@/lib/mock-data";

export default function Home() {
  return <AppLayout>
    <section className="relative overflow-hidden bg-[#f1f7f1]">
      <div className="absolute -left-28 top-10 size-72 rounded-full bg-[#dcefe5]/70 blur-3xl" />
      <div className="absolute right-[-10%] top-[-20%] size-[620px] rounded-full bg-[#f0d7cb]/35 blur-3xl" />
      <div className="container relative grid min-h-[660px] items-center gap-12 pb-16 pt-12 lg:grid-cols-[0.9fr_1.1fr] lg:gap-8 lg:pb-20 lg:pt-16">
        <div className="relative z-10 max-w-xl">
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }} className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#cbe2d2] bg-white/70 px-3.5 py-2 text-[11px] font-bold uppercase tracking-[0.13em] text-[#146b5a]"><span className="size-1.5 rounded-full bg-[#b8443e]" /> Care, without the runaround</motion.div>
          <motion.h1 initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55, delay: 0.06 }} className="font-display text-[52px] font-semibold leading-[0.96] tracking-[-0.075em] text-[#17342f] sm:text-[68px]">Find care that <span className="text-[#146b5a]">feels considered.</span></motion.h1>
          <motion.p initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55, delay: 0.12 }} className="mt-6 max-w-md text-[16px] leading-7 text-[#63736e]">Discover trusted hospitals, compare the right doctors, and book an appointment that fits your day — all in one calmer place.</motion.p>
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55, delay: 0.18 }} className="mt-8"><SearchBar /></motion.div>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.5, delay: 0.28 }} className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-3 text-xs font-semibold text-[#6d8178]"><span className="inline-flex items-center gap-2"><ShieldCheck size={15} className="text-[#146b5a]" /> Verified care partners</span><span className="inline-flex items-center gap-2"><Clock3 size={15} className="text-[#146b5a]" /> Same-day slots</span></motion.div>
        </div>
        <motion.div initial={{ opacity: 0, scale: 0.98, x: 18 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ duration: 0.7, delay: 0.1 }} className="relative mx-auto w-full max-w-[630px] lg:ml-auto">
          <div className="absolute -left-5 top-16 z-10 hidden rounded-2xl border border-white/70 bg-white/90 p-3 shadow-[0_16px_35px_rgba(26,61,52,0.12)] sm:block"><div className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-[#e3f2e8] text-[#146b5a]"><Check size={16} strokeWidth={3} /></span><div><div className="text-[11px] font-bold text-[#17342f]">Trusted by families</div><div className="mt-0.5 text-[10px] font-semibold text-[#8a9994]">12k+ appointments booked</div></div></div></div>
          <div className="overflow-hidden rounded-[34px] border-[10px] border-white/60 bg-white shadow-[0_22px_60px_rgba(24,69,57,0.15)]"><picture><source srcSet="/hero-doctor-consultation.webp" type="image/webp" /><img src="/hero-doctor-consultation.jpg" alt="A patient speaking with a doctor in a bright clinic" className="aspect-[4/3] w-full object-cover" /></picture></div>
          <div className="absolute -bottom-7 -right-3 max-w-[245px] rounded-[22px] border border-white/80 bg-[#103e38] p-4 text-white shadow-[0_18px_35px_rgba(15,63,55,0.2)] sm:-right-6"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#f0b1a5] text-[#71352f]"><Stethoscope size={17} /></span><div><div className="text-[11px] font-bold text-white/55">Next available</div><div className="mt-1 text-sm font-bold">Dr. Ananya Rao · 4:30 PM</div></div></div></div>
        </motion.div>
      </div>
      <div className="container relative pb-8"><div className="grid grid-cols-2 gap-3 border-t border-[#cfe2d6] pt-6 sm:grid-cols-4 sm:gap-0"><HeroMetric value="1,200+" label="verified care partners" /><HeroMetric value="4.8/5" label="average patient rating" /><HeroMetric value="18 min" label="average booking time" /><HeroMetric value="24/7" label="care navigation support" /></div></div>
    </section>

    <section className="container py-20 sm:py-28" id="how-it-works">
      <SectionHeading eyebrow="A better way to book" title="Less searching. More certainty." body="DocX brings the details people actually need together, so a visit starts with clarity instead of a dozen open tabs." action={<Link href="/hospitals" className="hidden items-center gap-2 text-sm font-bold text-[#146b5a] sm:inline-flex">See all care options <ArrowRight size={15} /></Link>} />
      <div className="mt-12 grid gap-4 md:grid-cols-3"><Step number="01" icon={<MapPin size={21} />} title="Choose your care" body="Search by hospital, specialty, doctor, or the care you need today." /><Step number="02" icon={<UsersRound size={21} />} title="Compare with context" body="See ratings, fees, facilities, visiting doctors, and open times at a glance." /><Step number="03" icon={<Clock3 size={21} />} title="Book with confidence" body="Pick a time, share your reason for visiting, and keep every detail in one place." /></div>
    </section>

    <section className="bg-[#f1f7f1] py-20 sm:py-24"><div className="container"><SectionHeading eyebrow="Start here" title="Care that’s close to your life." body="A focused directory of trusted hospitals and doctors, beginning with Bengaluru's most relied-on care teams." action={<Link href="/hospitals" className="hidden items-center gap-2 rounded-full bg-[#146b5a] px-4 py-3 text-xs font-bold text-white transition hover:bg-[#0e4c42] sm:inline-flex">Browse directory <ArrowRight size={14} /></Link>} /><div className="mt-10 grid gap-5 lg:grid-cols-2"><HospitalCard hospital={hospitals[0]} featured /><HospitalCard hospital={hospitals[1]} featured /></div><div className="mt-5 flex justify-center sm:hidden"><Link href="/hospitals" className="inline-flex items-center gap-2 rounded-full bg-[#146b5a] px-4 py-3 text-xs font-bold text-white">Browse directory <ArrowRight size={14} /></Link></div></div></section>

    <section className="container py-20 sm:py-28"><SectionHeading eyebrow="Meet your care team" title="Good doctors. Clear next steps." body="Profiles that make it easy to understand a doctor's expertise, availability, and the hospitals where they see patients." action={<Link href="/hospitals" className="hidden items-center gap-2 text-sm font-bold text-[#146b5a] sm:inline-flex">Find a doctor <ArrowRight size={15} /></Link>} /><div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-5">{doctors.slice(0, 3).map((doctor) => <DoctorCard key={doctor.id} doctor={doctor} />)}</div></section>

    <section className="bg-[#fbfaf6] pb-20 sm:pb-28"><div className="container grid gap-5 lg:grid-cols-2"><AssistantCard /><VoiceReminderCard /></div></section>

    <section className="bg-[#103e38] py-20 sm:py-24"><div className="container"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><div className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#f0b1a5]">A little more ease</div><h2 className="mt-3 font-display text-3xl font-semibold leading-[1.04] tracking-[-0.05em] text-white sm:text-[44px]">“I finally felt like someone had thought this through.”</h2></div><div className="grid gap-3 sm:grid-cols-3">{testimonials.map((item, index) => <div key={item.name} className={`rounded-[22px] p-5 ${index === 1 ? "bg-[#f0b1a5] text-[#71352f]" : "bg-white/10 text-white"}`}><div className="flex items-center gap-1 text-[#f5c36a]">★★★★★</div><p className={`mt-4 text-sm leading-6 ${index === 1 ? "text-[#7d443c]" : "text-white/75"}`}>“{item.quote}”</p><div className="mt-5 flex items-center gap-2.5"><span className={`grid size-8 place-items-center rounded-full text-[10px] font-bold ${index === 1 ? "bg-[#d9887b] text-[#71352f]" : "bg-white/15 text-white"}`}>{item.initials}</span><div><div className="text-xs font-bold">{item.name}</div><div className={`mt-0.5 text-[10px] ${index === 1 ? "text-[#9c5c53]" : "text-white/45"}`}>{item.meta}</div></div></div></div>)}</div></div></div></section>

    <section className="container py-20 sm:py-24"><div className="relative overflow-hidden rounded-[32px] bg-[#eaf3ed] px-6 py-12 sm:px-12 sm:py-16"><div className="absolute -right-24 -top-28 size-80 rounded-full bg-[#d0e8d6]" /><div className="relative max-w-2xl"><TrustPill><ShieldCheck size={13} /> Thoughtful by design</TrustPill><h2 className="mt-5 font-display text-3xl font-semibold leading-[1.04] tracking-[-0.05em] text-[#17342f] sm:text-[48px]">Your next appointment should be the easiest thing on your calendar.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-[#63736e]">Start with a care search, and let DocX take care of the details. Your future self will thank you.</p><Link href="/hospitals" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#146b5a] px-5 py-3.5 text-sm font-bold text-white transition hover:bg-[#0e4c42]">Find care near you <ArrowRight size={15} /></Link></div></div></section>
  </AppLayout>;
}

function HeroMetric({ value, label }: { value: string; label: string }) { return <div className="border-[#cfe2d6] px-0 first:pl-0 sm:border-l sm:px-6 sm:first:border-l-0 sm:first:pl-0"><div className="font-display text-2xl font-semibold tracking-[-0.05em] text-[#17342f]">{value}</div><div className="mt-1 text-[11px] font-semibold text-[#78918a]">{label}</div></div>; }
function Step({ number, icon, title, body }: { number: string; icon: React.ReactNode; title: string; body: string }) { return <motion.div whileHover={{ y: -4 }} className="rounded-[24px] border border-[#dfe9e4] bg-white p-6 shadow-[0_10px_30px_rgba(26,61,52,0.04)]"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#e3f2e8] text-[#146b5a]">{icon}</span><span className="font-mono text-xs font-bold text-[#b6c6bf]">{number}</span></div><h3 className="mt-7 font-display text-xl font-semibold tracking-[-0.04em] text-[#17342f]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#78918a]">{body}</p><ChevronRight size={18} className="mt-5 text-[#b8443e]" /></motion.div>; }
